# Generated by Django 4.0.5 on 2022-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_menumoneys'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumoneys',
            name='coin',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='menumoneys',
            name='diamond',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='menumoneys',
            name='level',
            field=models.IntegerField(default=5),
        ),
    ]
